---
- name: Configure wireguard server
  hosts: hetzner_vpn
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Import tasks to configure the wireguard server
      ansible.builtin.import_tasks: tasks/wireguard_server.yml

- name: Configure wireguard client
  hosts: localhost
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Import tasks to configure the wireguard client
      ansible.builtin.import_tasks: tasks/wireguard_client.yml

- name: Copy public keys
  hosts: hetzner_vpn
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Import copy public key tasks
      ansible.builtin.import_tasks: tasks/copy_public_key.yml
