---
- hosts: hetzner_vpn
  vars_files:
    - vars/vars.yml

  tasks:
    - import_tasks: tasks/wireguard_server.yml

- hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - import_tasks: tasks/wireguard_client.yml

- hosts: hetzner_vpn
  vars_files:
    - vars/vars.yml

  tasks:
    - import_tasks: tasks/copy_public_key.yml
