---
- name: Cleanup
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Block
      block:
        - name: Wait for containers to be up
          ansible.builtin.wait_for_connection:
            delay: 1
            timeout: 2
          register: connection
          ignore_errors: yes

        - name: Containers are not up, quit from here
          ansible.builtin.fail:
          when: connection['failed']

        - name: Delete vpn server
          hetzner.hcloud.hcloud_server:
            name: vpn
            api_token: "{{ lookup('ansible.builtin.env', 'HCLOUD_TOKEN') }}"
            state: absent
          when: lookup('ansible.builtin.env', 'type') == "vpn"

        - name: Delete vpn ssh key
          hetzner.hcloud.hcloud_ssh_key:
            name: vpn_ssh_key
            api_token: "{{ lookup('ansible.builtin.env', 'HCLOUD_TOKEN') }}"
            state: absent
          when: lookup('ansible.builtin.env', 'type') == "vpn"

        - name: Delete minecraft server
          hetzner.hcloud.hcloud_server:
            name: minecraft
            api_token: "{{ lookup('ansible.builtin.env', 'HCLOUD_TOKEN') }}"
            state: absent
          when: lookup('ansible.builtin.env', 'type') == "minecraft"

        - name: Delete minecraft ssh key
          hetzner.hcloud.hcloud_ssh_key:
            name: minecraft_ssh_key
            api_token: "{{ lookup('ansible.builtin.env', 'HCLOUD_TOKEN') }}"
            state: absent
          when: lookup('ansible.builtin.env', 'type') == "minecraft"

      rescue:
        - name: It's ok we're at startup
          ansible.builtin.meta: noop
