---
- name: Update packages
  ansible.builtin.apt:
    update_cache: yes
    upgrade: "yes"

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present
