---
- name: Configure minecraft server
  hosts: hetzner_minecraft
  become: yes
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Import tasks to configure the minecraft server
      ansible.builtin.import_tasks: tasks/minecraft_server.yml
