---
- name: Copy public key
  lineinfile:
    dest: /etc/wireguard/wg.conf
    regexp: "^#PublicKey = Test"
    line: "PublicKey = {{ hostvars['localhost'].wireguard__fact_public_key }}"

- name: Start and enable wireguard service
  ansible.builtin.service:
    name: wg-quick@wg
    state: started
    enabled: yes
