---
- hosts: localhost
  vars_files:
    - vars/vars.yml
  tasks:
    - import_tasks: tasks/hetzner_management.yml

- hosts: hetzner_{{ type }}
  vars_files:
    - vars/vars.yml
  tasks:
    - import_tasks: tasks/initial_config.yml

- name: Configure wireguard
  import_playbook: ../configure_wireguard/configure_wireguard.yml
  when: type == "vpn"

- name: Configure minecraft server
  import_playbook: ../configure_minecraft/configure_minecraft.yml
  when: type == "minecraft"
