---
- name: Create server on https://www.hetzner.com/cloud
  hosts: localhost
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Import tasks for server creation
      ansible.builtin.import_tasks: tasks/hetzner_management.yml

- name: Initial config
  hosts: hetzner_{{ lookup('ansible.builtin.env', 'type') }}
  become: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Import tasks for initial config
      ansible.builtin.import_tasks: tasks/initial_config.yml

- name: Configure wireguard
  import_playbook: ../configure_wireguard/configure_wireguard.yml
  when: lookup('ansible.builtin.env', 'type') == "vpn"

- name: Configure minecraft server
  import_playbook: ../configure_minecraft/configure_minecraft.yml
  when: lookup('ansible.builtin.env', 'type') == "minecraft"
