---
hetzner:
  hosts:
    hetzner_vpn:
      ansible_host:
        "{{ lookup('ansible.builtin.env',
        'DUCKDNS_DOMAIN_VPN') }}.duckdns.org"
      ansible_user: root
      ansible_connection: ssh
      ansible_ssh_private_key_file:
        "{{ lookup('ansible.builtin.env', 'GITHUB_WORKSPACE')
        }}/.ssh/vpn_ssh_key"
    hetzner_minecraft:
      ansible_host:
        "{{ lookup('ansible.builtin.env',
        'DUCKDNS_DOMAIN_MINECRAFT') }}.duckdns.org"
      ansible_user: root
      ansible_connection: ssh
      ansible_ssh_private_key_file:
        "{{ lookup('ansible.builtin.env', 'GITHUB_WORKSPACE')
        }}/.ssh/minecraft_ssh_key"
