name: build docker container and scan the container with snyk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install_ssh_keys_and_build_docker_container:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key of vpn server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_VPN }}
          name: kbkm-vpn
          known_hosts: unnecessary
          config: |
            Host kbkm-vpn.duckdns.org
               IdentityFile ~/.ssh/kbkm-vpn
               StrictHostKeyChecking no
               UserKnownHostsFile=/dev/null
      - name: Install SSH key of minecraft server
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY_MINECRAFT }}
          name: kbkm-minecraft
          known_hosts: unnecessary
          config: |                                         # will be appended to existing .ssh/config
            Host kbkm-minecraft.duckdns.org
               IdentityFile ~/.ssh/kbkm-minecraft
               StrictHostKeyChecking no
               UserKnownHostsFile=/dev/null
      - name: Print location of ssh file
        run: echo $(ls -la /home/runner/.ssh)
        shell: bash

      - uses: actions/checkout@v2
      - name: Copy ssh key
        run: |
          cp /home/runner/.ssh/kbkm-vpn /home/runner/work/KBKM-Bot/KBKM-Bot/
          cp /home/runner/.ssh/kbkm-minecraft /home/runner/work/KBKM-Bot/KBKM-Bot/
        shell: bash
      - name: Print location of ssh file
        run: echo $(ls -la /home/runner/work/KBKM-Bot/KBKM-Bot)
        shell: bash
      - name: Setup up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: tobdocker/kbkm-bot:latest         
      - name: Snyk Container Test
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ Secrets.SNYK_TOKEN }}
        with:
          image: tobdocker/kbkm-bot:latest
          args: --file=Dockerfile
